### PR TITLE
changed EOL on installer.sh

### PR DESCRIPTION
**Pull request by galenemery**

### CODE REVIEW

**Comment by galenemery** [comment]
I don't think it actually committed the EOL change.

**Comment by stephenlauck** [comment]
galen [3:57 PM] 
So, it appears that when you pull the repo on Windows, git converts the EOL to CRLF vs when you pull it on Unix, the EOL is LF.  The issue comes down to the chef-server does not understand the CRLF ending on the installer.sh, after it's been transferred over, and thus can't run the script.

**Comment by stephenlauck** [comment]
I need to try this on windows to confirm.

**Comment by galenemery** [comment]
Closing PR in favor of @grdnrio 's fix to modify the .gitattributes file to ensure that all .sh files are left in the correct format.

**Pull request closed without merging**
